version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
      - CELERY_RESULT_BACKEND=rpc://

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    command: celery -A tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
      - CELERY_RESULT_BACKEND=rpc://

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"       # RabbitMQ broker port
      - "15672:15672"     # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
